# Generated by Django 3.2.7 on 2022-03-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_familiar',
            field=models.BooleanField(default=False, help_text='Do you have any experience with using python?', verbose_name='Python'),
        ),
    ]
