# Generated by Django 3.2.7 on 2022-04-07 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_familiar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_learned',
        ),
    ]
