# Generated by Django 3.2.7 on 2022-03-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_is_familiar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_learned',
            field=models.BooleanField(default=False, help_text='Have you learned programming before?', verbose_name='False'),
        ),
    ]
