# Generated by Django 3.2.7 on 2022-04-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='course',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='name',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='sub_topic',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='topic',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='pdf',
            field=models.FileField(default='curriculum.pdf', upload_to='mediafiles/'),
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
