# Generated by Django 3.2.7 on 2022-03-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='url',
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(choices=[(1, 'Django Web Framework'), (2, 'Data Analysis'), (3, 'Data Science')], max_length=50),
        ),
    ]
