# Generated by Django 3.2.7 on 2022-04-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20220414_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='image.jpg', upload_to='mediafiles/'),
        ),
    ]
