# Generated by Django 3.2.7 on 2022-04-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(choices=[('DS', 'Data Science'), ('DA', 'Data Analysis'), ('DJ', 'Django Web Framework'), ('DR', 'Django REST Framework')], default='Data Science', max_length=50),
        ),
    ]
