# Generated by Django 3.2.7 on 2022-03-29 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='country',
            field=django_countries.fields.CountryField(default='NG', max_length=2, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='student',
            name='student',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='country',
            field=django_countries.fields.CountryField(default='NG', max_length=2, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
    ]
