# Generated by Django 3.2.7 on 2022-03-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='students',
        ),
        migrations.AddField(
            model_name='teacher',
            name='students',
            field=models.ManyToManyField(to='membership.Student'),
        ),
    ]
