# Generated by Django 3.2.7 on 2022-04-07 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20220407_2012'),
        ('membership', '0002_auto_20220330_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='country',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
        migrations.AddField(
            model_name='student',
            name='is_familiar',
            field=models.BooleanField(default=False, help_text='Do you have any experience with using python?', verbose_name='Python'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_learned',
            field=models.BooleanField(default=False, help_text='Have you learned programming before?', verbose_name='False'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
